name: Auto-approve PR with

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
#      pr_number:
#        required: true
#        type: number
      base_branch:
        required: true
        type: string
      head_branch:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  auto-approve:
    runs-on: [ "self-hosted", "brokkr"]
    container:
      image: kirschbaumdevelopment/laravel-test-runner:${{ inputs.php-version }}

    steps:
      - uses: actions/checkout@v4

      - run: git fetch origin ${{ inputs.base_branch }} ${{ inputs.head_branch }}

      - name: Check if only composer.lock changed
        id: check_lock
        run: |
          files=$(git diff --name-only origin/${{ inputs.base_branch }} origin/${{ inputs.head_branch }})
          echo "Changed files: $files"
          if [ "$files" = "composer.lock" ]; then
            echo "only_lock=1" >> $GITHUB_OUTPUT
          else
            echo "only_lock=0" >> $GITHUB_OUTPUT
          fi

      - name: Approve PR
        if: steps.check_lock.outputs.only_lock == '1'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}