name: Laravel Code Style Analysis (docker)

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      php-extensions:
        required: false
        type: string
        default: '[]'
      extensions:
        required: false
        type: string
        default: '[]'

jobs:
  laravel-code-style:
    runs-on: [ "self-hosted", "docker"]
    # container:
    #   image: kirschbaumdevelopment/laravel-test-runner:${{ inputs.php-version }}

    services:
      mysql:
        image: mariadb:10.11.6
        env:
          MARIADB_ROOT_PASSWORD: test
          MARIADB_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Update repositories
        run: sudo apt-get update
      - name: Install extensions
        if: ${{ inputs.extensions != '[]' }}
        run: |
          sudo apt install ${{ join(fromJSON(inputs.extensions), ' ') }} -y

      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
      - uses: php-actions/composer@v6
        with:
          php_version: "8.3"

      - name: Execute PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix app --dry-run --diff
